import type { Tournament, Team, Player, Match, Referee, Coach, MatchEvent } from "./types"

export const sampleTournaments: Tournament[] = [
  {
    id: "t1",
    name: "Liga Amateur 2025",
    format: "11",
    startDate: "2025-01-15",
    endDate: "2025-06-30",
    status: "active",
    organizerId: "admin",
    teamIds: ["team1", "team2", "team3", "team4"],
    rules: "Torneo de liga, todos contra todos. Puntos: 3 por victoria, 1 por empate.",
  },
  {
    id: "t2",
    name: "Copa Primavera",
    format: "7",
    startDate: "2025-03-01",
    endDate: "2025-04-15",
    status: "upcoming",
    organizerId: "admin",
    teamIds: ["team5", "team6"],
    rules: "Eliminación directa. En caso de empate, penales.",
  },
  {
    id: "t3",
    name: "Torneo Relámpago",
    format: "5",
    startDate: "2025-02-10",
    endDate: "2025-02-11",
    status: "upcoming",
    organizerId: "admin",
    teamIds: [],
    rules: "Fútbol 5, partidos de 30 minutos",
  },
]

export const sampleTeams: Team[] = [
  {
    id: "team1",
    name: "Tigres FC",
    tournamentId: "t1",
    foundedDate: "2020-01-01",
    coachId: "coach1",
  },
  {
    id: "team2",
    name: "Águilas United",
    tournamentId: "t1",
    foundedDate: "2019-05-15",
    coachId: "coach2",
  },
  {
    id: "team3",
    name: "Leones SC",
    tournamentId: "t1",
    foundedDate: "2021-03-10",
    coachId: "coach3",
  },
  {
    id: "team4",
    name: "Pumas CF",
    tournamentId: "t1",
    foundedDate: "2018-11-20",
  },
  {
    id: "team5",
    name: "Halcones FC",
    tournamentId: "t2",
    foundedDate: "2022-08-05",
  },
  {
    id: "team6",
    name: "Lobos United",
    tournamentId: "t2",
    foundedDate: "2023-01-12",
  },
]

export const samplePlayers: Player[] = [
  // Tigres FC
  {
    id: "p1",
    name: "Carlos Mendoza",
    teamId: "team1",
    position: "Portero",
    number: 1,
    birthDate: "1995-03-15",
    nationality: "México",
    height: 185,
    weight: 80,
    dominantFoot: "right",
    email: "carlos.mendoza@email.com",
    phone: "+52 123 456 7801",
    bloodType: "O+",
  },
  {
    id: "p2",
    name: "Juan Pérez",
    teamId: "team1",
    position: "Defensa",
    number: 2,
    birthDate: "1997-06-22",
    nationality: "México",
    height: 178,
    weight: 75,
    dominantFoot: "right",
    email: "juan.perez@email.com",
    phone: "+52 123 456 7802",
    bloodType: "A+",
  },
  {
    id: "p3",
    name: "Luis García",
    teamId: "team1",
    position: "Defensa",
    number: 3,
    birthDate: "1996-11-08",
    nationality: "México",
    height: 182,
    weight: 78,
    dominantFoot: "left",
    email: "luis.garcia@email.com",
    phone: "+52 123 456 7803",
    bloodType: "B+",
  },
  {
    id: "p4",
    name: "Miguel Torres",
    teamId: "team1",
    position: "Defensa",
    number: 4,
    birthDate: "1998-01-30",
    nationality: "México",
    height: 180,
    weight: 76,
    dominantFoot: "right",
    email: "miguel.torres@email.com",
    phone: "+52 123 456 7804",
  },
  {
    id: "p5",
    name: "Javier Ramírez",
    teamId: "team1",
    position: "Medio",
    number: 5,
    birthDate: "1997-09-14",
    nationality: "México",
    height: 175,
    weight: 72,
    dominantFoot: "both",
    email: "javier.ramirez@email.com",
    phone: "+52 123 456 7805",
    bloodType: "O-",
  },
  {
    id: "p6",
    name: "Roberto Silva",
    teamId: "team1",
    position: "Medio",
    number: 8,
    birthDate: "1995-12-05",
    nationality: "México",
    height: 177,
    weight: 74,
    dominantFoot: "right",
    email: "roberto.silva@email.com",
    phone: "+52 123 456 7806",
  },
  {
    id: "p7",
    name: "Andrés Moreno",
    teamId: "team1",
    position: "Medio",
    number: 10,
    birthDate: "1994-07-20",
    nationality: "México",
    height: 173,
    weight: 70,
    dominantFoot: "left",
    email: "andres.moreno@email.com",
    phone: "+52 123 456 7807",
    bloodType: "AB+",
  },
  {
    id: "p8",
    name: "Fernando López",
    teamId: "team1",
    position: "Delantero",
    number: 9,
    birthDate: "1996-04-18",
    nationality: "México",
    height: 181,
    weight: 77,
    dominantFoot: "right",
    email: "fernando.lopez@email.com",
    phone: "+52 123 456 7808",
  },
  {
    id: "p9",
    name: "Diego Hernández",
    teamId: "team1",
    position: "Delantero",
    number: 11,
    birthDate: "1998-08-25",
    nationality: "México",
    height: 176,
    weight: 73,
    dominantFoot: "right",
    email: "diego.hernandez@email.com",
    phone: "+52 123 456 7809",
    bloodType: "A-",
  },
  {
    id: "p29",
    name: "Adrián Domínguez",
    teamId: "team1",
    position: "Defensa",
    number: 6,
    birthDate: "1997-03-11",
    nationality: "México",
    height: 179,
    weight: 75,
    dominantFoot: "right",
    email: "adrian.dominguez@email.com",
    phone: "+52 123 456 7829",
    bloodType: "A+",
  },
  {
    id: "p30",
    name: "Iván Campos",
    teamId: "team1",
    position: "Medio",
    number: 7,
    birthDate: "1996-08-19",
    nationality: "México",
    height: 174,
    weight: 71,
    dominantFoot: "left",
    email: "ivan.campos@email.com",
    phone: "+52 123 456 7830",
    bloodType: "O+",
  },

  // Águilas United
  {
    id: "p10",
    name: "Sergio Martínez",
    teamId: "team2",
    position: "Portero",
    number: 1,
    birthDate: "1994-05-12",
    nationality: "México",
    height: 188,
    weight: 83,
    dominantFoot: "right",
    email: "sergio.martinez@email.com",
    phone: "+52 123 456 7810",
    bloodType: "O+",
  },
  {
    id: "p11",
    name: "Pablo Sánchez",
    teamId: "team2",
    position: "Defensa",
    number: 2,
    birthDate: "1997-02-28",
    nationality: "México",
    height: 179,
    weight: 76,
    dominantFoot: "right",
    email: "pablo.sanchez@email.com",
    phone: "+52 123 456 7811",
  },
  {
    id: "p12",
    name: "Ricardo Flores",
    teamId: "team2",
    position: "Defensa",
    number: 3,
    birthDate: "1996-10-15",
    nationality: "México",
    height: 183,
    weight: 79,
    dominantFoot: "left",
    email: "ricardo.flores@email.com",
    phone: "+52 123 456 7812",
    bloodType: "B+",
  },
  {
    id: "p13",
    name: "Omar Castillo",
    teamId: "team2",
    position: "Defensa",
    number: 4,
    birthDate: "1998-03-07",
    nationality: "México",
    height: 181,
    weight: 77,
    dominantFoot: "right",
    email: "omar.castillo@email.com",
    phone: "+52 123 456 7813",
  },
  {
    id: "p14",
    name: "Alberto Ruiz",
    teamId: "team2",
    position: "Medio",
    number: 6,
    birthDate: "1995-11-19",
    nationality: "México",
    height: 174,
    weight: 71,
    dominantFoot: "both",
    email: "alberto.ruiz@email.com",
    phone: "+52 123 456 7814",
    bloodType: "A+",
  },
  {
    id: "p15",
    name: "Gustavo Vega",
    teamId: "team2",
    position: "Medio",
    number: 8,
    birthDate: "1997-07-03",
    nationality: "México",
    height: 176,
    weight: 73,
    dominantFoot: "right",
    email: "gustavo.vega@email.com",
    phone: "+52 123 456 7815",
  },
  {
    id: "p16",
    name: "Emilio Cruz",
    teamId: "team2",
    position: "Medio",
    number: 10,
    birthDate: "1994-09-21",
    nationality: "México",
    height: 172,
    weight: 69,
    dominantFoot: "left",
    email: "emilio.cruz@email.com",
    phone: "+52 123 456 7816",
    bloodType: "O-",
  },
  {
    id: "p17",
    name: "Raúl Navarro",
    teamId: "team2",
    position: "Delantero",
    number: 9,
    birthDate: "1996-01-11",
    nationality: "México",
    height: 180,
    weight: 76,
    dominantFoot: "right",
    email: "raul.navarro@email.com",
    phone: "+52 123 456 7817",
  },
  {
    id: "p18",
    name: "Héctor Ortiz",
    teamId: "team2",
    position: "Delantero",
    number: 11,
    birthDate: "1998-06-08",
    nationality: "México",
    height: 178,
    weight: 75,
    dominantFoot: "left",
    email: "hector.ortiz@email.com",
    phone: "+52 123 456 7818",
    bloodType: "AB+",
  },
  {
    id: "p31",
    name: "Rubén Estrada",
    teamId: "team2",
    position: "Defensa",
    number: 5,
    birthDate: "1996-04-25",
    nationality: "México",
    height: 180,
    weight: 77,
    dominantFoot: "right",
    email: "ruben.estrada@email.com",
    phone: "+52 123 456 7831",
    bloodType: "B+",
  },
  {
    id: "p32",
    name: "Julio Mendoza",
    teamId: "team2",
    position: "Medio",
    number: 7,
    birthDate: "1997-09-14",
    nationality: "México",
    height: 175,
    weight: 72,
    dominantFoot: "right",
    email: "julio.mendoza@email.com",
    phone: "+52 123 456 7832",
    bloodType: "O-",
  },

  // Leones SC
  {
    id: "p19",
    name: "Arturo Vargas",
    teamId: "team3",
    position: "Portero",
    number: 1,
    birthDate: "1995-04-09",
    nationality: "México",
    height: 186,
    weight: 81,
    dominantFoot: "right",
    email: "arturo.vargas@email.com",
    phone: "+52 123 456 7819",
  },
  {
    id: "p20",
    name: "Marco Delgado",
    teamId: "team3",
    position: "Defensa",
    number: 2,
    birthDate: "1997-08-16",
    nationality: "México",
    height: 180,
    weight: 77,
    dominantFoot: "right",
    email: "marco.delgado@email.com",
    phone: "+52 123 456 7820",
    bloodType: "A+",
  },
  {
    id: "p21",
    name: "Víctor Medina",
    teamId: "team3",
    position: "Defensa",
    number: 3,
    birthDate: "1996-12-22",
    nationality: "México",
    height: 182,
    weight: 78,
    dominantFoot: "left",
    email: "victor.medina@email.com",
    phone: "+52 123 456 7821",
  },
  {
    id: "p22",
    name: "Rodrigo Jiménez",
    teamId: "team3",
    position: "Medio",
    number: 8,
    birthDate: "1995-10-05",
    nationality: "México",
    height: 175,
    weight: 72,
    dominantFoot: "right",
    email: "rodrigo.jimenez@email.com",
    phone: "+52 123 456 7822",
    bloodType: "O+",
  },
  {
    id: "p23",
    name: "Ángel Reyes",
    teamId: "team3",
    position: "Medio",
    number: 10,
    birthDate: "1994-03-28",
    nationality: "México",
    height: 173,
    weight: 70,
    dominantFoot: "both",
    email: "angel.reyes@email.com",
    phone: "+52 123 456 7823",
  },
  {
    id: "p24",
    name: "César Aguilar",
    teamId: "team3",
    position: "Delantero",
    number: 9,
    birthDate: "1997-05-13",
    nationality: "México",
    height: 179,
    weight: 75,
    dominantFoot: "right",
    email: "cesar.aguilar@email.com",
    phone: "+52 123 456 7824",
    bloodType: "B+",
  },
  {
    id: "p33",
    name: "Cristian Luna",
    teamId: "team3",
    position: "Defensa",
    number: 4,
    birthDate: "1998-02-07",
    nationality: "México",
    height: 181,
    weight: 77,
    dominantFoot: "right",
    email: "cristian.luna@email.com",
    phone: "+52 123 456 7833",
    bloodType: "A+",
  },
  {
    id: "p34",
    name: "Oscar Salazar",
    teamId: "team3",
    position: "Defensa",
    number: 5,
    birthDate: "1996-06-15",
    nationality: "México",
    height: 179,
    weight: 76,
    dominantFoot: "left",
    email: "oscar.salazar@email.com",
    phone: "+52 123 456 7834",
    bloodType: "O+",
  },
  {
    id: "p35",
    name: "Bruno Cortés",
    teamId: "team3",
    position: "Medio",
    number: 6,
    birthDate: "1997-11-22",
    nationality: "México",
    height: 174,
    weight: 71,
    dominantFoot: "right",
    email: "bruno.cortes@email.com",
    phone: "+52 123 456 7835",
    bloodType: "B-",
  },
  {
    id: "p36",
    name: "Samuel Ríos",
    teamId: "team3",
    position: "Medio",
    number: 7,
    birthDate: "1995-09-03",
    nationality: "México",
    height: 176,
    weight: 73,
    dominantFoot: "both",
    email: "samuel.rios@email.com",
    phone: "+52 123 456 7836",
    bloodType: "AB+",
  },
  {
    id: "p37",
    name: "Leonardo Paredes",
    teamId: "team3",
    position: "Delantero",
    number: 11,
    birthDate: "1998-04-29",
    nationality: "México",
    height: 178,
    weight: 74,
    dominantFoot: "right",
    email: "leonardo.paredes@email.com",
    phone: "+52 123 456 7837",
    bloodType: "O-",
  },

  // Pumas CF
  {
    id: "p25",
    name: "Mauricio Guzmán",
    teamId: "team4",
    position: "Portero",
    number: 1,
    birthDate: "1996-07-30",
    nationality: "México",
    height: 187,
    weight: 82,
    dominantFoot: "right",
    email: "mauricio.guzman@email.com",
    phone: "+52 123 456 7825",
  },
  {
    id: "p26",
    name: "Daniel Rojas",
    teamId: "team4",
    position: "Defensa",
    number: 2,
    birthDate: "1997-11-24",
    nationality: "México",
    height: 181,
    weight: 78,
    dominantFoot: "right",
    email: "daniel.rojas@email.com",
    phone: "+52 123 456 7826",
    bloodType: "A-",
  },
  {
    id: "p27",
    name: "Alejandro Peña",
    teamId: "team4",
    position: "Medio",
    number: 8,
    birthDate: "1995-02-17",
    nationality: "México",
    height: 176,
    weight: 73,
    dominantFoot: "left",
    email: "alejandro.pena@email.com",
    phone: "+52 123 456 7827",
  },
  {
    id: "p28",
    name: "Gabriel Morales",
    teamId: "team4",
    position: "Delantero",
    number: 9,
    birthDate: "1998-09-02",
    nationality: "México",
    height: 180,
    weight: 76,
    dominantFoot: "right",
    email: "gabriel.morales@email.com",
    phone: "+52 123 456 7828",
    bloodType: "O+",
  },
]

export const sampleReferees: Referee[] = [
  {
    id: "ref1",
    name: "Mario Hernández",
    license: "FIFA-2024-001",
    experience: 10,
    email: "mario.h@ligasmart.com",
    phone: "+52 123 456 7890",
  },
  {
    id: "ref2",
    name: "Ricardo Sánchez",
    license: "NAC-2023-045",
    experience: 5,
    email: "ricardo.s@ligasmart.com",
    phone: "+52 123 456 7891",
  },
  {
    id: "ref3",
    name: "Fernando Lara",
    license: "NAC-2024-012",
    experience: 8,
    email: "fernando.l@ligasmart.com",
    phone: "+52 123 456 7892",
  },
]

export const sampleCoaches: Coach[] = [
  {
    id: "coach1",
    name: "Alberto Gómez",
    license: "UEFA B",
    experience: 15,
    email: "alberto.g@ligasmart.com",
    phone: "+52 234 567 8901",
    specialty: "Fútbol Ofensivo",
  },
  {
    id: "coach2",
    name: "Rafael Morales",
    license: "CONMEBOL Pro",
    experience: 8,
    email: "rafael.m@ligasmart.com",
    phone: "+52 234 567 8902",
    specialty: "Táctica Defensiva",
  },
  {
    id: "coach3",
    name: "Jorge Campos",
    license: "UEFA A",
    experience: 12,
    email: "jorge.c@ligasmart.com",
    phone: "+52 234 567 8903",
    specialty: "Desarrollo Juvenil",
  },
]

export const sampleMatches: Match[] = [
  {
    id: "m1",
    tournamentId: "t1",
    homeTeamId: "team1",
    awayTeamId: "team2",
    date: "2025-01-20",
    time: "16:00",
    venue: "Estadio Municipal",
    status: "finished",
    homeScore: 2,
    awayScore: 1,
    refereeId: "ref1",
  },
  {
    id: "m2",
    tournamentId: "t1",
    homeTeamId: "team3",
    awayTeamId: "team4",
    date: "2025-01-20",
    time: "18:00",
    venue: "Campo Deportivo Central",
    status: "finished",
    homeScore: 1,
    awayScore: 1,
    refereeId: "ref2",
  },
  {
    id: "m3",
    tournamentId: "t1",
    homeTeamId: "team1",
    awayTeamId: "team3",
    date: "2025-01-27",
    time: "16:00",
    venue: "Estadio Municipal",
    status: "finished",
    homeScore: 3,
    awayScore: 0,
    refereeId: "ref1",
  },
  {
    id: "m4",
    tournamentId: "t1",
    homeTeamId: "team2",
    awayTeamId: "team4",
    date: "2025-01-27",
    time: "18:00",
    venue: "Campo Sur",
    status: "finished",
    homeScore: 2,
    awayScore: 2,
    refereeId: "ref3",
  },
  {
    id: "m5",
    tournamentId: "t1",
    homeTeamId: "team1",
    awayTeamId: "team4",
    date: "2025-02-03",
    time: "16:00",
    venue: "Estadio Municipal",
    status: "scheduled",
    refereeId: "ref1",
  },
  {
    id: "m6",
    tournamentId: "t1",
    homeTeamId: "team2",
    awayTeamId: "team3",
    date: "2025-02-03",
    time: "18:00",
    venue: "Campo Deportivo Central",
    status: "scheduled",
    refereeId: "ref2",
  },
]

export const sampleMatchEvents: MatchEvent[] = [
  // Match 1: Tigres 2 - 1 Águilas
  {
    id: "e1",
    matchId: "m1",
    type: "goal",
    playerId: "p8",
    teamId: "team1",
    minute: 15,
    description: "Gol de Fernando López",
  },
  {
    id: "e2",
    matchId: "m1",
    type: "goal",
    playerId: "p17",
    teamId: "team2",
    minute: 34,
    description: "Gol de Raúl Navarro",
  },
  {
    id: "e3",
    matchId: "m1",
    type: "yellow_card",
    playerId: "p11",
    teamId: "team2",
    minute: 45,
    description: "Falta táctica",
  },
  {
    id: "e4",
    matchId: "m1",
    type: "goal",
    playerId: "p7",
    teamId: "team1",
    minute: 67,
    description: "Gol de Andrés Moreno",
  },

  // Match 2: Leones 1 - 1 Pumas
  {
    id: "e5",
    matchId: "m2",
    type: "goal",
    playerId: "p24",
    teamId: "team3",
    minute: 23,
    description: "Gol de César Aguilar",
  },
  { id: "e6", matchId: "m2", type: "yellow_card", playerId: "p26", teamId: "team4", minute: 38 },
  {
    id: "e7",
    matchId: "m2",
    type: "goal",
    playerId: "p28",
    teamId: "team4",
    minute: 72,
    description: "Gol de Gabriel Morales",
  },

  // Match 3: Tigres 3 - 0 Leones
  {
    id: "e8",
    matchId: "m3",
    type: "goal",
    playerId: "p8",
    teamId: "team1",
    minute: 12,
    description: "Gol de Fernando López",
  },
  {
    id: "e9",
    matchId: "m3",
    type: "goal",
    playerId: "p9",
    teamId: "team1",
    minute: 35,
    description: "Gol de Diego Hernández",
  },
  { id: "e10", matchId: "m3", type: "yellow_card", playerId: "p20", teamId: "team3", minute: 54 },
  {
    id: "e11",
    matchId: "m3",
    type: "goal",
    playerId: "p8",
    teamId: "team1",
    minute: 78,
    description: "Doblete de Fernando López",
  },

  // Match 4: Águilas 2 - 2 Pumas
  {
    id: "e12",
    matchId: "m4",
    type: "goal",
    playerId: "p17",
    teamId: "team2",
    minute: 8,
    description: "Gol de Raúl Navarro",
  },
  {
    id: "e13",
    matchId: "m4",
    type: "goal",
    playerId: "p28",
    teamId: "team4",
    minute: 25,
    description: "Gol de Gabriel Morales",
  },
  {
    id: "e14",
    matchId: "m4",
    type: "goal",
    playerId: "p16",
    teamId: "team2",
    minute: 56,
    description: "Gol de Emilio Cruz",
  },
  { id: "e15", matchId: "m4", type: "yellow_card", playerId: "p14", teamId: "team2", minute: 68 },
  {
    id: "e16",
    matchId: "m4",
    type: "goal",
    playerId: "p27",
    teamId: "team4",
    minute: 85,
    description: "Gol de Alejandro Peña",
  },
]

export const initializeSampleData = () => {
  const existingTournaments = localStorage.getItem("ligasmart_tournaments")
  if (!existingTournaments || JSON.parse(existingTournaments).length === 0) {
    localStorage.setItem("ligasmart_tournaments", JSON.stringify(sampleTournaments))
    localStorage.setItem("ligasmart_teams", JSON.stringify(sampleTeams))
    localStorage.setItem("ligasmart_players", JSON.stringify(samplePlayers))
    localStorage.setItem("ligasmart_referees", JSON.stringify(sampleReferees))
    localStorage.setItem("ligasmart_coaches", JSON.stringify(sampleCoaches))
    localStorage.setItem("ligasmart_matches", JSON.stringify(sampleMatches))
    localStorage.setItem("ligasmart_match_events", JSON.stringify(sampleMatchEvents))
  }
}
